# Change these first
owner: amara060
repo: upptime

sites:
  - name: Twin Cities
    url: https://twin-cities.umn.edu/?uptime_test

  - name: Duluth
    url: https://duluth.umn.edu/?uptime_test

  - name: Morris
    url: https://morris.umn.edu/?uptime_test

  - name: KJK
    url: https://kjkk.umn.edu/?uptime_test

status-website:
  # Use GitHub Pages
  baseUrl: /upptime

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: University of Minnesota Website Monitoring
  introTitle: "University of Minnesota Website Monitoring"
  introMessage: >
    Automated monitoring of University of Minnesota websites,
    including Twin Cities, Duluth, and Morris campuses.

  navbar:
    - title: Status
      href: /

    - title: GitHub
      href: https://github.com/amara060/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
